### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by andycochran** [rvega/wordpress-widget-network-recent-posts#1]
Thanks for this plugin. I'm just having one issue with it. On [line 93](https://github.com/rvega/wordpress-widget-network-recent-posts/blob/master/recent-posts-network.php#L93), `krsort($found_posts);` doesn't seem to get the order right. The posts seem to be ordered randomly.

**Comment by andycochran** [comment]
I think I've got this working by changing `post_modified` to `post_date` line 83: 

``` php
$found_posts[$post->post_date] = array(
```

What is the reason for using `$post->post_modified`?

**Comment by rvega** [comment]
Post modification date vs post creation date. I guess it's a matter of what you need for your use case.

**Comment by andycochran** [comment]
That makes sense. Thanks.
